/**
 * Pre-optimized responsive image (AVIF → WebP fallback). Files are generated by
 * .claude/skills/image-optimization/scripts/optimize_images.mjs as `<base>-<width>.<ext>`.
 */
type Props = {
  base: string; // e.g. "/img/catch-night"
  widths: number[];
  width: number; // intrinsic size of the largest file, for aspect ratio (no CLS)
  height: number;
  alt: string;
  sizes: string;
  className?: string;
  eager?: boolean;
};

export function Picture({ base, widths, width, height, alt, sizes, className, eager }: Props) {
  const set = (ext: string) => widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(", ");
  const largest = Math.max(...widths);
  return (
    <picture>
      <source type="image/avif" srcSet={set("avif")} sizes={sizes} />
      <img
        src={`${base}-${largest}.webp`}
        srcSet={set("webp")}
        sizes={sizes}
        width={width}
        height={height}
        alt={alt}
        className={className}
        loading={eager ? "eager" : "lazy"}
        fetchPriority={eager ? "high" : undefined}
        decoding={eager ? "sync" : "async"}
      />
    </picture>
  );
}

/** A product bag image: a single width (the source crops are small — see README "Imagini"). */
export function BagImage({ base, width, height, alt, className, eager }: { base: string; width: number; height: number; alt: string; className?: string; eager?: boolean }) {
  return (
    <picture>
      <source type="image/avif" srcSet={`${base}.avif`} />
      <img src={`${base}.webp`} width={width} height={height} alt={alt} className={className} loading={eager ? "eager" : "lazy"} decoding="async" />
    </picture>
  );
}
