import { shot } from "@/lib/projects";

// <picture> with AVIF + WebP srcsets generated by the image-optimization skill script.
export function Shot({
  slug, view, alt, sizes, eager = false, className,
}: { slug: string; view: "desktop" | "mobile"; alt: string; sizes: string; eager?: boolean; className?: string }) {
  const s = shot(slug, view);
  return (
    <picture>
      <source type="image/avif" srcSet={s.avif} sizes={sizes} />
      <img
        src={s.src} srcSet={s.webp} sizes={sizes} width={s.width} height={s.height} alt={alt}
        loading={eager ? "eager" : "lazy"} fetchPriority={eager ? "high" : "auto"} decoding="async"
        className={className}
      />
    </picture>
  );
}
