import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Reveal } from "@/components/shared/Reveal";
import { Button } from "@/components/ui/Button";
import { withBasePath } from "@/lib/basePath";
import { clientProjects, portfolioItems } from "@/lib/constants";

// Shown behind the screenshot while it loads, as the fallback if it ever
// fails, and as the whole tile for a live project that has no screenshot yet
// — the tile never collapses to an empty box.
const patterns = [
  "var(--gradient-blue-cyan)",
  "var(--gradient-blue-purple)",
  "var(--gradient-purple-pink)",
  "var(--gradient-blue-cyan)",
];

// Deliberately uneven: the grid alternates 7/5 and 5/7 so the row rhythm
// never settles into the uniform 2x2 the rest of the web defaults to.
const spans = ["lg:col-span-7", "lg:col-span-5", "lg:col-span-5", "lg:col-span-7"];
const heights = ["lg:h-[30rem]", "lg:h-[30rem]", "lg:h-[26rem]", "lg:h-[26rem]"];

// The screenshots range from near-black (Ember) to near-white (Haven), so the
// band behind the caption is fully opaque rather than merely dark: over the
// light shots, a translucent scrim left the demo's own headline showing
// through our title. The shot still reads clearly above the fold of the band.
const SCRIM =
  "linear-gradient(to top, #050816 0%, #050816 34%, rgba(5,8,22,0.90) 48%, rgba(5,8,22,0.42) 72%, rgba(5,8,22,0.08) 100%)";

type Tile = {
  id: string;
  href: string;
  preview?: string;
  previewPosition?: string;
  category: string;
  title: string;
  description: string;
};

/**
 * One tile, used for both a delivered project and a demo. The only real
 * difference is the badge and whether the link leaves the site — a live
 * project opens in a new tab, because sending someone away from the page
 * that is supposed to convert them is a bad trade.
 */
function ProjectTile({
  item,
  index,
  badge,
  external,
}: {
  item: Tile;
  index: number;
  badge: string;
  external: boolean;
}) {
  const shared = `group relative block h-80 overflow-hidden rounded-lg focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-accent-2 sm:h-96 ${heights[index % heights.length]}`;

  const inner = (
    <>
      <div className="absolute inset-0" style={{ background: patterns[index % patterns.length] }} />

      {/* Plain <img> on purpose: this is a static export with
          images.unoptimized, so next/image would add runtime code without
          optimising anything, and its preload path emits an unprefixed URL
          under a subpath build. The demos' shots are regenerated by
          scripts/generate-previews.py; a live project's is added by hand. */}
      {item.preview ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={withBasePath(item.preview)}
          alt={`Captură din site-ul ${item.title}`}
          width={1200}
          height={750}
          loading="lazy"
          decoding="async"
          // Ember centres its hero, the rest align left. On a phone the tile
          // is nearly square, so a fixed anchor would slice the headline off
          // one of them either way.
          style={{ objectPosition: item.previewPosition }}
          className="absolute inset-0 size-full object-cover transition-transform duration-[900ms] ease-[var(--ease-premium)] group-hover:scale-[1.05]"
        />
      ) : null}

      {/* Fără captură, cardul nu are ce întuneca: scrimul complet l-ar face
          să pară o imagine care nu s-a încărcat. Atunci se întunecă doar
          partea de jos, cât să se citească textul peste gradient. */}
      <div
        className="absolute inset-0"
        style={{
          background: item.preview
            ? SCRIM
            : "linear-gradient(to top, rgba(5,8,22,0.94) 0%, rgba(5,8,22,0.86) 34%, rgba(5,8,22,0.45) 62%, rgba(5,8,22,0.1) 100%)",
        }}
      />
      {/* On a phone the caption is three lines tall on a shorter tile, so it
          runs past the scrim's solid band. This extra layer covers that case
          without darkening desktop. */}
      <div
        className="absolute inset-0 sm:hidden"
        style={{ background: "linear-gradient(to top, #050816 0%, #050816 54%, transparent 100%)" }}
      />
      {/* Slight darkening at the very top so the badge doesn't sit directly
          on the captured site's own navigation. */}
      <div
        className="absolute inset-x-0 top-0 h-24"
        style={{ background: "linear-gradient(to bottom, rgba(5,8,22,0.6), transparent)" }}
      />

      <span className="absolute right-4 top-4 rounded-full bg-black/45 px-3 py-1 text-[0.65rem] font-bold uppercase tracking-[0.08em] text-white backdrop-blur-sm">
        {badge}
      </span>

      {!item.preview ? (
        <span
          className="font-display absolute left-6 top-1/2 max-w-[80%] -translate-y-[60%] text-2xl font-semibold text-white/85 sm:left-7 sm:text-3xl"
          aria-hidden="true"
        >
          {item.href.replace("https://", "").replace(/\/$/, "")}
        </span>
      ) : null}

      <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-4 p-6 sm:p-7">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.1em] text-white/80">{item.category}</p>
          <h3 className="font-display mt-2 text-2xl font-semibold text-white transition-transform duration-500 ease-[var(--ease-premium)] group-hover:-translate-y-0.5 sm:text-3xl">
            {item.title}
          </h3>
          <p className="mt-2 max-w-sm text-sm leading-relaxed text-white/85">{item.description}</p>
        </div>

        <span className="flex size-12 shrink-0 items-center justify-center rounded-full border border-white/35 bg-black/25 backdrop-blur-sm transition-all duration-500 ease-[var(--ease-premium)] group-hover:rotate-45 group-hover:border-white group-hover:bg-white">
          <ArrowUpRight
            className="size-5 text-white transition-colors duration-500 group-hover:text-black"
            aria-hidden="true"
          />
        </span>
      </div>
    </>
  );

  if (external) {
    return (
      <a href={item.href} target="_blank" rel="noopener" className={shared}>
        {inner}
      </a>
    );
  }

  return (
    <Link href={item.href} className={shared}>
      {inner}
    </Link>
  );
}

export function Portfolio() {
  return (
    <section id="portofoliu" className="section-y relative">
      <div className="container-max px-5 sm:px-8 lg:px-10">
        <Reveal className="grid gap-6 lg:grid-cols-12 lg:items-end">
          <h2 className="font-display text-4xl font-semibold tracking-tight text-foreground sm:text-5xl lg:col-span-6">
            Site-uri construite de noi
          </h2>
          <p className="text-sm leading-relaxed text-muted-foreground lg:col-span-5 lg:col-start-8">
            Întâi proiectele livrate, online acum, pe domeniile clienților. Sub ele, patru site-uri demo pe care
            le poți folosi exact ca pe unele reale — meniuri, coș de cumpărături, filtre, formulare.
          </p>
        </Reveal>

        {/* Proiectele livrate stau primele și ocupă fiecare jumătate de rând.
            Un site real al unui client cântărește mai mult decât orice demo,
            oricât de bine construit ar fi demo-ul. */}
        {clientProjects.length ? (
          <>
            <Reveal className="mt-14">
              <h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-accent-2">Proiecte livrate</h3>
            </Reveal>
            <div className="mt-6 grid gap-5 sm:gap-6 lg:grid-cols-12">
              {clientProjects.map((item, i) => (
                <Reveal key={item.id} delay={i * 0.07} className="lg:col-span-6">
                  <ProjectTile item={item} index={i} badge="Proiect live" external />
                </Reveal>
              ))}
            </div>
          </>
        ) : null}

        <Reveal className="mt-16">
          <h3 className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">
            Demo-uri — concepte construite de noi, nu afaceri reale
          </h3>
        </Reveal>
        <div className="mt-6 grid gap-5 sm:gap-6 lg:grid-cols-12">
          {portfolioItems.map((item, i) => (
            <Reveal key={item.id} delay={i * 0.07} className={spans[i % spans.length]}>
              <ProjectTile item={item} index={i} badge="Demo Concept" external={false} />
            </Reveal>
          ))}
        </div>

        <Reveal delay={0.15} className="mt-10 flex justify-center">
          <Button href="#contact" variant="outline" icon={false} className="rounded-full">
            Discută un proiect asemănător
          </Button>
        </Reveal>
      </div>
    </section>
  );
}
